name: hello_world
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
# environment:
#   sdk: ">=2.1.0 <3.0.0"

dependencies:
  functional_widget_annotation: ^0.5.1
  rxdart: 0.22.1+1
  flutter:
    sdk: flutter

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  functional_widget: ^0.7.1
  build_runner: ^1.9.0

flutter:
  uses-material-design: true
# builders:
#   functional_widget: ^0.6.0
